baseURL: /
languageCode: en-us
title: MohannadNaj.me
theme: papercss-hugo-theme
disqusShortname: mohannadnaj-me
defaultContentLanguage: en
languages:
  en:
    languagedirection: ltr
    LanguageName: English - Technical Blog
    weight: 1
  ar:
    languagedirection: rtl
    LanguageName: المدونة العربية
    weight: 2
    menu:
      main:
        - name: سِمات
          weight: 2
          url: ar/tags/
    homeInfoParams:
      Title: Mohannad Najjar - المدونة العربية
      Content: >-
        هنا مساحة للتدوين والكتابة

permalinks:
  ar: /:filename
  posts: /en/:slug
params:
  ShowReadingTime: true
  comments: true
  displayFullLangName: true
  homeInfoParams:
    Title: My name is Mohannad Najjar
    Content: >-
      A blog about Web Development, Software Engineering, Laravel stack, Open
      source and more
  socialIcons:
    - name: github
      url: https://github.com/MohannadNaj/
    - name: linkedin
      url: https://linkedin.com/in/MohannadNaj/
    - name: twitter
      url: https://twitter.com/MohannadNaj
menu:
  main:
    - name: Blog
      weight: 1
      url: /posts/
    - name: Tags
      weight: 2
      url: /tags/
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    lineNoStart: 1
    lineNos: false
    tabWidth: 4
